#-*- coding:utf-8 -*-
#!/usr/bin/env python
execfile('AmezMallH5_001_Login.py')
execfile('AmezMallH5_002_LoginFromMyPage.py')
execfile('AmezMallH5_003_AddToCart.py')
execfile('AmezMallH5_004_BuyGoods.py')
execfile('AmezMallH5_005_OrderProcess.py')
execfile('AmezMallH5_006_RefundForShipment.py')
execfile('AmezMallH5_007_RefundForGoodsToBeReceived.py')
execfile('AmezMallH5_008_ReceivedRefund.py')
execfile('AmezMallH5_009_FailureToRefundShipment.py')
execfile('AmezMallH5_010_FailureToReceiveRefund.py')
execfile('AmezMallH5_011_FailedReceiptRefund.py')
execfile('AmezMallH5_012_MerchantsIssueCoupons.py')
execfile('AmezMallH5_013_UseCoupons.py')
# execfile('AmezMallH5_014_CouponExpired.py')