#-*- coding:utf-8 -*-
#!/usr/bin/env python
execfile('AmezMallUI_001_Login.py')
execfile('AmezMallUI_002_SearchGood.py')
execfile('AmezMallUI_003_AddToCart.py')
execfile('AmezMallUI_004_BuyGood.py')
execfile('AmezMallUI_005_OrderProcess.py')
execfile('AmezMallUI_006_RefundForShipment.py')
execfile('AmezMallUI_007_RefundForGoodsToBeReceived.py')
execfile('AmezMallUI_008_ReceivedRefund.py')
execfile('AmezMallUI_009_FailureToRefundShipment.py')
execfile('AmezMallUI_010_FailureToReceiveRefund.py')
execfile('AmezMallUI_011_FailedReceiptRefund.py')
execfile('AmezMallUI_012_MerchantsIssueCoupons.py')
execfile('AmezMallUI_013_ReceivesCoupons.py')
execfile('AmezMallUI_014_UseCoupons.py')
execfile('AmezMallUI_015_CouponExpired.py')
execfile('AmezMallUI_016_IntegralMallSearchProduct.py')
execfile('AmezMallUI_017_IntegralMallBuyGoods.py')
execfile('AmezMallUI_019_InsufficientInventoryOfGoods.py')
execfile('AmezMallUI_020_ModifyInventory.py')